### ISSUE TITLE
More config options?

### ISSUE THREAD

**Issue by jmatsushita** [dockhippie/mariadb#1]
Thanks for the cool image!

I found myself wanting to configure other aspects of the image specifically:

```
[mysqld]
innodb-file-format=barracuda
innodb-file-per-table=1
innodb-large-prefix=1
character-set-client-handshake = FALSE
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci
```

Probably others would benefit from either adding some variables to your ENV templating,or maybe adding `!includedir` to a `/etc/mysql/conf.d` folder ?

**Comment by tboerger** [comment]
Cool that somebody else finds it useful. If you got sane default values I'm open for new options, otherwise a conf folder as a volume would also work fine. I think I had something like that back when this image was based on Debian.

**Comment by jmatsushita** [comment]
Cool, there you go :)

**Comment by tboerger** [comment]
Thanks
