### ISSUE TITLE
Issues with ownCloud

### ISSUE THREAD

**Issue by daAftermath** [dockhippie/mariadb#14]
this is my docker-compose.yml

    version: '2.1'

    volumes:
        files:
            driver: local
        mysql:
            driver: local
        backup:
            driver: local
        redis:
            driver: local

    services:
        owncloud:
            image: owncloud/server:latest
            restart: always
            ports:
            - 8585:8080
        depends_on:
            - db
            - redis
        environment:
            - OWNCLOUD_DOMAIN= localhost
            - OWNCLOUD_DB_TYPE= mysql
            - OWNCLOUD_DB_NAME= owncloud
            - OWNCLOUD_DB_USERNAME= owncloud
            - OWNCLOUD_DB_PASSWORD= owncloud
            - OWNCLOUD_DB_HOST= db
            - OWNCLOUD_ADMIN_USERNAME= admin
            - OWNCLOUD_ADMIN_PASSWORD= admin
            - OWNCLOUD_MYSQL_UTF8MB4= true
            - OWNCLOUD_REDIS_HOST= redis
        healthcheck:
            test: ["CMD", "/usr/bin/healthcheck"]
            interval: 30s
            timeout: 10s
            retries: 5
        volumes:
            - files:/mnt/data

    db:
        image: webhippie/mariadb:latest
        restart: always
        environment:
            - MARIADB_ROOT_PASSWORD= owncloud
            - MARIADB_USERNAME= owncloud
            - MARIADB_PASSWORD= owncloud
            - MARIADB_DATABASE= owncloud
            - MARIADB_MAX_ALLOWED_PACKET= 128M
            - MARIADB_INNODB_LOG_FILE_SIZE= 64M
        healthcheck:
            test: ["CMD", "/usr/bin/healthcheck"]
            interval: 30s
            timeout: 10s
            retries: 5
        volumes:
            - mysql:/var/lib/mysql
            - backup:/var/lib/backup

    redis:
        image: webhippie/redis:latest
        restart: always
        environment:
            - REDIS_DATABASES=1
        healthcheck:
            test: ["CMD", "/usr/bin/healthcheck"]
            interval: 30s
            timeout: 10s
            retries: 5
        volumes:
            - redis:/var/lib/redis`

This the error i am getting
`Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'owncloud'@'docker_owncloud_1.docker_default' (using password: YES)`
![err](https://user-images.githubusercontent.com/44099426/54131055-ce997c00-43ce-11e9-8eca-8d4ab39f5e9e.PNG)

i contacted docker support and am told that the issue is with database.

**Comment by tboerger** [comment]
Since this error happens with both MariaDB images this sounds like a network issue on your server. For reference, first reported at https://github.com/owncloud-docker/server/issues/117.

**Comment by daAftermath** [comment]
I think its the default port in mariadb. How can i change that

**Comment by tboerger** [comment]
There is no configuration variable to change that.
