### ISSUE TITLE
Duplicate ENV entries

### ISSUE THREAD

**Issue by demyxco** [dockhippie/mariadb#24]
These are the 3 environments listed as duplicates. Any reason why you posted them twice?

MARIADB_KEY_BUFFER_SIZE
MARIADB_SORT_BUFFER_SIZE
MARIADB_READ_BUFFER

**Comment by tboerger** [comment]
Why would that happen? Only by accident... Everything else doesn't make sense ;)

**Comment by demyxco** [comment]
Haha yeah I know how you feel. I'm using your image for my CLI docker wrapper stack in my repo. Feel free to close this! Not really an issue, just wondering if you're aware :)

**Comment by tboerger** [comment]
Solved
