### ISSUE TITLE
tzdata not installed, no timezone settings

### ISSUE THREAD

**Issue by tanus10** [dockhippie/mariadb#25]
Without tzdata installed in the image, TZ does not work as expected, results inability to set a timezone.
Manually installing with 'apk add tzdata' within the image makes it work though.
I know it's a common problem for alpine based docker image. Is there another way to fix this other than installing tzdata manually inside the image?

**Comment by tboerger** [comment]
Maybe you want to create a PR to fix that? In which case does this issue occur?

**Comment by tanus10** [comment]
I am sure you know well the common ways to set a timezone in a container.

in docker-compose.yml
```
environment:
        - "TZ=Asia/Hongkong"
```
or
```
      volumes:
        - /etc/localtime:/etc/localtime:ro
```

Alpine base usually focuses on the size of the image, so it would be a choice whether or not to support timezone setting. But, without it, log outputs will be confusing, if it's a DB server image, then DB configuration must be changed to set a timezone, not to use system(image/container) timezone.
```
[mariadb]
...
default_time_zone = 'America/New_York';
```

FYI, tzdata said to be add 3MB to the image, but it seems there is someway to deal with it by enabling timezone setting with 'apk add tzdata -> copy wanted zone file to /etc/localtime -> apk del tzdata' which I googled. However, for some reason, with your image I cannot do that if I do apk del tzdata.

**Comment by tboerger** [comment]
I have create a PR now that just installs tzdata: https://github.com/dockhippie/mariadb/pull/29

**Comment by tanus10** [comment]
Just confirmed working! Thanks.
