### ISSUE TITLE
Added BUG FIX, made it more complete and DRY

### ISSUE THREAD

**Issue by learningnewthings** [dockhippie/mariadb#3]
**Disclaimer**: I'm a **noob** with regards to bash, git, mysql, docker.
First time writting bash. **(Untested Code, Syntax Check required)**
(If you want a PULL request, I'll test the code and I'll do it. I'm currently virgin:D)

Added **FIX** for: **https://github.com/dockhippie/mariadb/blob/master/rootfs/etc/s6/mariadb/run**
The code from line **32** to **44** is **buggy + incomplete + not dry**.

**The buggy code:**
If both MARIADB_USERNAME and MARIADB_DATABASE are specified, it will create **2 DBs**.
If MARIADB_DATABASE is specified, but MARIADB_USERNAME is missing, it does **Not** create a DB.
```
if [[ -n "${MARIADB_USERNAME}" && -n "${MARIADB_DATABASE}" ]]
then
  echo "CREATE DATABASE IF NOT EXISTS \`${MARIADB_USERNAME}\`;" >> ${INIT_FILE}
  echo "GRANT ALL PRIVILEGES ON \`${MARIADB_DATABASE}\`.* TO '${MARIADB_USERNAME}'@'%' IDENTIFIED BY '${MARIADB_PASSWORD}';" >> ${INIT_FILE}
  echo "FLUSH PRIVILEGES;" >> ${INIT_FILE}
fi

if [[ -n "${MARIADB_USERNAME}" && -z "${MARIADB_DATABASE}" ]]
then
  echo "CREATE DATABASE IF NOT EXISTS \`${MARIADB_USERNAME}\`;" >> ${INIT_FILE}
  echo "GRANT ALL PRIVILEGES ON \`${MARIADB_USERNAME}\`.* TO '${MARIADB_USERNAME}'@'%' IDENTIFIED BY '${MARIADB_PASSWORD}';" >> ${INIT_FILE}
  echo "FLUSH PRIVILEGES;" >> ${INIT_FILE}
fi
```

**The FIXED code:**

```
NEW_DB__NAME="$(MARIADB_DATABASE:-$MARIADB_USERNAME)"
if [ ! -z "${NEW_DB__NAME}" ]
then
  echo "CREATE DATABASE IF NOT EXISTS \`${NEW_DB__NAME}\`;" >> ${INIT_FILE}

  NEW_DB__USER="$(MARIADB_USERNAME:-root)"
  if [ "$NEW_DB__USER" != "root" ]
  then
    echo "GRANT ALL PRIVILEGES ON \`${NEW_DB__NAME}\`.* TO '${NEW_DB__USER}'@'%' IDENTIFIED BY '${MARIADB_PASSWORD}';" >> ${INIT_FILE}
    echo "FLUSH PRIVILEGES;" >> ${INIT_FILE}
  fi
fi
```

Lemme know if anything,
Kind Regards,
Me.

**Comment by tboerger** [comment]
> If both MARIADB_USERNAME and MARIADB_DATABASE are specified, it will create 2 DBs.

I don't think so. The conditions are partially different so I can not confirm that it creates 2 databases...

**Comment by tboerger** [comment]
https://github.com/dockhippie/mariadb/blob/master/rootfs/etc/s6/mariadb/run#L34 got a bug that it creates a database named by MARIADB_USERNAME instead of MARIADB_DATABASE.

**Comment by learningnewthings** [comment]
I was partially wrong, I realized after testing, but you didn't responded so I didn't insist.
I had 2 DBs , because your script created the wrong database (named MARIADB_USERNAME), and my wordpress seeing that the database (named MARIADB_DATABASE) is missing was creating it, so I end up with 2 DBs.

In my code above I have a small syntax errors: () , instead of {}. (no worries, I give you new tested code)

Bug#2 Your code doesn't treat the case if MARIADB_DATABASE is set, but MARIADB_USERNAME is not set.
(in this case the user should default to root)

Bug#3 I tested and fails to create a user with no password when MARIADB_USERNAME is set but MARIADB_PASSWORD is not set.

I already have tested code, I'll add a check for MARIADB_PASSWORD not set, then I'll paste the tested code here... in a few hours (need to install docker.... and retest)

P.S. The main problem with your code (other then the wrong DB name) is that it checks for only 2 cases, when it should treat all the possible combinations of set or unset MARIADB_DATABASE , MARIADB_USERNAME , MARIADB_PASSWORD

**Comment by learningnewthings** [comment]
Done. Created a pull request.

The code is tested. The new code is smaller and it checks for all possible combinations of set or unset MARIADB_USERNAME, MARIADB_PASSWORD & MARIADB_DATABASE. The change was:

**From this:**
`if [[ -n "${MARIADB_USERNAME}" && -n "${MARIADB_DATABASE}" ]]
then
  echo "CREATE DATABASE IF NOT EXISTS \`${MARIADB_USERNAME}\`;" >> ${INIT_FILE}
  echo "GRANT ALL PRIVILEGES ON \`${MARIADB_DATABASE}\`.* TO '${MARIADB_USERNAME}'@'%' IDENTIFIED BY '${MARIADB_PASSWORD}';" >> ${INIT_FILE}
  echo "FLUSH PRIVILEGES;" >> ${INIT_FILE}
fi

if [[ -n "${MARIADB_USERNAME}" && -z "${MARIADB_DATABASE}" ]]
then
  echo "CREATE DATABASE IF NOT EXISTS \`${MARIADB_USERNAME}\`;" >> ${INIT_FILE}
  echo "GRANT ALL PRIVILEGES ON \`${MARIADB_USERNAME}\`.* TO '${MARIADB_USERNAME}'@'%' IDENTIFIED BY '${MARIADB_PASSWORD}';" >> ${INIT_FILE}
  echo "FLUSH PRIVILEGES;" >> ${INIT_FILE}
fi`

**To this:**
`if [[ -n "${MARIADB_USERNAME}" && -n "${MARIADB_DATABASE}" ]]
then
  echo "CREATE DATABASE IF NOT EXISTS \`${MARIADB_USERNAME}\`;" >> ${INIT_FILE}
  echo "GRANT ALL PRIVILEGES ON \`${MARIADB_DATABASE}\`.* TO '${MARIADB_USERNAME}'@'%' IDENTIFIED BY '${MARIADB_PASSWORD}';" >> ${INIT_FILE}
  echo "FLUSH PRIVILEGES;" >> ${INIT_FILE}
fi

if [[ -n "${MARIADB_USERNAME}" && -z "${MARIADB_DATABASE}" ]]
then
  echo "CREATE DATABASE IF NOT EXISTS \`${MARIADB_USERNAME}\`;" >> ${INIT_FILE}
  echo "GRANT ALL PRIVILEGES ON \`${MARIADB_USERNAME}\`.* TO '${MARIADB_USERNAME}'@'%' IDENTIFIED BY '${MARIADB_PASSWORD}';" >> ${INIT_FILE}
  echo "FLUSH PRIVILEGES;" >> ${INIT_FILE}
fi`
