### ISSUE TITLE
Default to turning off binary logging

### ISSUE THREAD

**Issue by golaat** [dockhippie/mariadb#32]
Does it really make sense to have binary logging defaulted to on in a containerized version of MariaDB? The logs are used for replication and to restore data after a backup -- but they also chew up a ton of volume space. At a minimum, it would be nice if the `expire_logs_days` environment variable was exposed.

Logs can be turned off by adding the following under the `[mysqld]` in the /etc/mysql/my.cnf:
`skip-log-bin`

**Comment by tboerger** [comment]
You can disable the log if you set MARIADB_LOG_BIN to 0. It's enabled by default because it had been the initial default and I wanted to avoid any breaking change.

**Comment by tboerger** [comment]
For reference: https://github.com/dockhippie/mariadb/blob/master/latest/overlay/etc/templates/my.cnf.tmpl#L27
