### ISSUE TITLE
mariadb restart loop since latest version on arm v6

### ISSUE THREAD

**Issue by jmeinicke** [dockhippie/mariadb#45]
Hi, 

2 days ago my webhippie/mariadb:latest  updated to the latest version. (watchtower)
@sha256:f0c65ccdf6d9c7842f9cdcc2292991727742e066b8836b83067f07e7dde657a6

Since this version I have problem on my rpi4. the container has a restart loop. the error is:

`203505-03-28 11:29:22 0 [ERROR] This server doesn't support dates later than 2038`

system time is okay. 

any ideas?

thank you

**Comment by tboerger** [comment]
If you are running it on a Raspberry Pi 4 it should be arm64 and not arm. I am running it on my Raspberry Pi 4 without a Problem, so not sure how to help with that.

**Comment by tboerger** [comment]
Have you found a solution for the problem?
