### ISSUE TITLE
Previous versions availability

### ISSUE THREAD

**Issue by loudjanilef** [dockhippie/mariadb#46]
Hello,
I recently updated my database to the new "latest" version of webhippie/mariadb. But the update went wront and the data is now innaccessible.
One possible fix would be to downgrade to last version (10.4.8) and upgrade again.
Therefore I cannot downgrade as only the "latest" version is available.
Is there a place where we can find images with specific webhippie/mariadb versions ?
I am using the image with digest sha256:f0c65ccdf6d9c7842f9cdcc2292991727742e066b8836b83067f07e7dde657a6
Thank you for your help

**Comment by tboerger** [comment]
Sadly there is currently only latest built from alpine:edge, there is no earlier version available. But why is the data not accessible anymore?

**Comment by loudjanilef** [comment]
Hi
Thank you for your answer
My error is the following
[ERROR] InnoDB: Upgrade after a crash is not supported. The redo log was created with MariaDB 10.4.8.
I tried multiple solutions without reverting to old mariadb but none of them worked.
I found this topic : https://jira.mariadb.org/browse/MDEV-23136 and It seems that with the old version i could be able to recover my files
The update to the new latest was done unexpectedly by my docker-compose and I probably didnt stop the old containers before upgrading.

**Comment by phynias** [comment]
in the same boat. upgraded and suddenly the container just restarts constantly. tried to start from scratch and load a dump but get the following error: 
ERROR 4047 (HY000) at line 25: InnoDB refuses to write tables with ROW_FORMAT=COMPRESSED or KEY_BLOCK_SIZE.

from what i can find online it seems most just revert back to 10.5

**Comment by phynias** [comment]
looks like the fix is adding innodb_read_only_compressed = 0 to the config.

**Comment by loudjanilef** [comment]
I finally was able to go back to version 10.4 using this image : https://hub.docker.com/r/yobasystems/alpine-mariadb/ which has labeled versions
After recovery, updating to 10.5 worked perfectly

**Comment by tboerger** [comment]
Since this image is directly built based on Alpine Edge packages there is not really a way back to the older MariaDB Version. Looks like it'S time to build it on my own...

**Comment by phynias** [comment]
you can install older version
find the package here: https://pkgs.alpinelinux.org/packages?name=mariadb&branch=v3.14
$ echo 'http://dl-cdn.alpinelinux.org/alpine/v3.14/main' >> /etc/apk/repositories
$ apk add 'mariadb==10.5.12-r0'
