### ISSUE TITLE
Volumn permission

### ISSUE THREAD

**Issue by brendaniel** [dockhippie/mariadb#5]
> I'm sorry to have to ask you here because I could not find any related posts.
> my docker-compose.yml

maria:
    image: webhippie/mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=
      - MARIADB_USERNAME=
      - MARIADB_PASSWORD=
      - MARIADB_DATABASE=
      - MARIADB_DEFAULT_CHARACTER_SET=utf8mb4
      - MARIADB_CHARACTER_SET_SERVER=utf8mb4
      - MARIADB_COLLATION_SERVER=utf8mb4_general_ci
    ports:
      - '3306:3306'
    expose:
      - '3306'
      - '3307'
    volumes:
      - ./maria/data:/var/lib/mysql
      - ./maria/backup:/var/lib/backup
      - ./maria/conf:/etc/mysql/conf.d

> run docker-compose up

maria_1      | Running mysql_install_db...
maria_1      | chown: /var/lib/mysql: Permission denied
maria_1      | Cannot change ownership of the database directories to the 'mysql'
maria_1      | user.  Check that you have the necessary permissions and try again.

> How can I give permissions to the mysql folder?

**Comment by brendaniel** [comment]
**solved**
https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker

**Comment by tboerger** [comment]
Great that you solved it on your own
