### ISSUE TITLE
Backup and Healthcheck

### ISSUE THREAD

**Issue by bibiak1** [dockhippie/mariadb#68]
Hi,

shouldn't /usr/bin/backup and /usr/bin/healthcheck be linked to /etc/periodic/daily and /etc/periodic/hourly ?

Maybe there's other way to enable auto backups and healthchecks?

**Comment by tboerger** [comment]
This is intentionally not done... Triggering backups should be done from outside, and healthcheck should be executed by Docker and not by cronjob.
